### ISSUE TITLE
2.2.0 broke stylelint 0.9.2

### ISSUE THREAD

**Issue by hashar** [kevva/dir-glob#10]
Hello,

On Wikimedia CI we are using stylelint which depends on:

stylelint@9.2.0 > globby@8.0.1 > dir-glob@2.2.0

Since 2.2.0 release, our style check fails with:
```
Running "stylelint:src" (stylelint) task
Warning: Path must be a string. Received undefined^G Use --force to continue.
```

A way to reproduce:
```
$ git clone --depth 1 https://gerrit.wikimedia.org/r/p/mediawiki/extensions/ContentTranslation
$ cd ContentTranslation
$ npm install
$ ./node_modules/.bin/grunt stylelint:src; echo "Exit code: $?"
Running "stylelint:src" (stylelint) task
Warning: Path must be a string. Received undefined Use --force to continue.

Aborted due to warnings.
Exit code: 3
$
```

I guess one of the issue is globby is too liberal in its version requirement (probably gets 2.*). Nevertheless, there seems to be a severe incompatibility in the dir-glob 2.2.0 version.

Our bug https://phabricator.wikimedia.org/T213249

**Comment by hashar** [comment]
globby v0.8.1 ( https://github.com/sindresorhus/globby/blob/v8.0.1/package.json ) has:
```
{
    "dependencies": {
        "dir-glob": "^2.0.0",
    }
}
```

Which previously matched 2.0.0 and now matches 2.2.0.

**Comment by TomVance** [comment]
We are also seeing similar issues and have opened an issue on globby. 

https://github.com/sindresorhus/globby/issues/98

**Comment by anastasiagryshchenko** [comment]
can confirm that this is an issue

stylelint is used like this `npx stylelint dir/**/*.less`

stackstrace:

```
09:33:41 TypeError: Path must be a string. Received undefined
09:33:41     at assertPath (path.js:28:11)
09:33:41     at Object.join (path.js:1236:7)
09:33:41     at getPath (/node_modules/dir-glob/index.js:6:41)```

**Comment by ThomasPedersen** [comment]
Seeing similar issues, with firebase (via globby)

**Comment by kevva** [comment]
Fixed in https://github.com/sindresorhus/globby/commit/d80422881de179c23726bbddd02c0402a797186b.
