### ISSUE TITLE
The cwd options must have a default value process.cwd()

### ISSUE THREAD

**Issue by Delan1026** [kevva/dir-glob#11]
`cwd` should have a default value: **process.cwd()**, if not, it will cause other related npm package run with errors! for example **globby**， **egg-bin test** depend on globby, `const files = globby.sync(pattern)` don't pass the options argument

**Comment by kevva** [comment]
It already [has](https://github.com/kevva/dir-glob/blob/master/index.js#L37). But if another value is passed in it'll use that instead. I don't think it's this modules responsibility to fix that.

There's a PR open for checking that it's set correctly though https://github.com/kevva/dir-glob/pull/8.
