### ISSUE TITLE
dir-glob does not transform directory syntax when using complex patterns.

### ISSUE THREAD

**Issue by xgbuils** [kevva/dir-glob#16]
Given a tree of files:
```
+ fixtures
  + foo.feature
  + bar.feature
```
`dir-glob` transform to glob syntax when using:
``` javascript
dirGlob.sync(['fixtures']) // ['fixtures/**']
```
But does not transform well when using:
``` javascript
dirGlob.sync(['f*s']) // ['f*s'] intead of ['f*s/**']
```

Notice that common apps like `eslint` also transform these patterns. For example, `eslint src` works at the same way as `eslint s*c`. And the same happens with files in `.eslintignore`.

Cheers!

**Comment by kevva** [comment]
That's because we can't know that `f*s` will resolve to a directory (`fixtures` in this case) without globbing first. We only add the `**` wildcard after checking if the path is a directory.

`f*s` could also resolve to a file, and then `f*s/**` wouldn't be a valid pattern.
