### ISSUE TITLE
Generated patterns in Windows are incompatible with micromatch

### ISSUE THREAD

**Issue by yhatt** [kevva/dir-glob#17]
dir-glob is using `path.join()` so it will use `\\` as join separator in Windows. It would not compatible with micromatch that reserves backslashes for escaping glob characters.
https://github.com/micromatch/micromatch/#backslashes

It means that the generated glob pattern may not work correctly in Windows environment.

```javascript
const dirGlob = require('dir-glob')
const micromatch = require('micromatch')

const patterns = dirGlob.sync(['lib'])

console.log(patterns)
console.log(micromatch(['lib/index.js'], patterns))
```

```bash
# POSIX environment
$ node ./test.js
[ 'lib/**' ]
[ 'lib/index.js' ]

# Windows
$ node ./test.js
[ 'lib\\**' ]
[]
```

I think we should always use slashes to join path by using `path.posix.join()`, or provide a option to choose how to join.

It came from working in the upgrade of fast-glob in globby's PR: https://github.com/sindresorhus/globby/pull/126#pullrequestreview-254632343

**Comment by sindresorhus** [comment]
I agree. Would you be interested in doing a PR?

**Comment by yhatt** [comment]
Sure. I'm going to work for PR if the suggested way is no problem.
