### ISSUE TITLE
`cwd` options not published on npm

### ISSUE THREAD

**Issue by pvdlg** [kevva/dir-glob#7]
Following the README example:

```bash
$ mkdir -p fixtures/inner_folder
$ touch fixtures/inner_folder/index.js
```

```js
dirGlob(['index.js', 'inner_folder'], {
	cwd: 'fixtures'
}).then(files => {
	console.log(files);
// => ['index.js', 'inner_folder'] and not ['index.js', 'inner_folder/**']
});
```

**Comment by pvdlg** [comment]
It seems it's because the code adding the `cwd` options wasn't released.
@kevva could you make a release with the last changes by any chance? Thanks a lot!

**Comment by pvdlg** [comment]
@kevva, really sorry to bother you again...Is there a chance you could release the last code from `master` on npm?
It's impacting `globby` users (https://github.com/sindresorhus/globby/issues/87) and requires [workarrounds on semantic-release](https://github.com/semantic-release/github/pull/96/commits/40d15763352b2f25b7123e029aae86ee142ca060)...

**Comment by sindresorhus** [comment]
It's published now.

**Comment by sindresorhus** [comment]
Oops, it's not.

**Comment by nambrot** [comment]
For anyone who might come here via pkg -> globby -> dir-glob, updating globby to 8.0.2 is probably the solution https://github.com/zeit/pkg/issues/603
